
POST http://localhost:8000/api/addFixed
Content-Type: application/json

{
  "start": 0,
  "id": "1-test",
  "cron": "25 * * * *"
}

###


POST http://localhost:8000/api/addFixed
Content-Type: application/json

{
  "start": 0,
  "id": "2-test",
  "cron": "* 13 * * *"
}

###

POST http://localhost:8000/api/addFixed
Content-Type: application/json

{
  "start": 0,
  "id": "3-test",
  "cron": "48 * * * *"
}

###

POST http://localhost:8000/api/addFixed
Content-Type: application/json

{
  "start": 0,
  "id": "4-test",
  "cron": "* * * * *"
}

###

POST http://localhost:8000/api/addFixed
Content-Type: application/json

{
  "start": 0,
  "id": "5-test",
  "cron": "* * * * *"
}

###


POST http://localhost:8000/api/addFixed
Content-Type: application/json

{
  "start": 0,
  "id": "6-test",
  "cron": "* * * * *"
}

###

